### ISSUE TITLE
Error when running api db test

### ISSUE THREAD

**Issue by arejay73** [bakerframework/bakercloud-ce-api#2]
When I comment out line number 170, the script work fine and validates.

Here is my error message:
Slim Application Error
The application could not run because of the following error:

Details

Code: 8
Message: Undefined variable: app_id
File: /var/www/pubapi/index.php
Line: 170
Trace
#0 /var/www/pubapi/index.php(170): Slim\Slim::handleErrors(8, 'Undefined varia...', '/var/www/pubapi...', 170, Array)
#1 [internal function]: {closure}()
#2 /var/www/pubapi/Slim/Router.php(200): call_user_func_array(Object(Closure), Array)
#3 /var/www/pubapi/Slim/Slim.php(1218): Slim\Router->dispatch(Object(Slim\Route))
#4 /var/www/pubapi/Slim/Middleware/Flash.php(86): Slim\Slim->call()
#5 /var/www/pubapi/Slim/Middleware/MethodOverride.php(94): Slim\Middleware\Flash->call()
#6 /var/www/pubapi/Slim/Middleware/PrettyExceptions.php(67): Slim\Middleware\MethodOverride->call()
#7 /var/www/pubapi/Slim/Slim.php(1167): Slim\Middleware\PrettyExceptions->call()
#8 /var/www/pubapi/index.php(884): Slim\Slim->run()
#9 {main}

**Comment by nin9creative** [comment]
I guess I don't understand the question.

**Comment by arejay73** [comment]
When going through the Baker Cloud Console API install on step 3. I get the error message mentioned above.
here is the link to documentation, http://docs.bakerframework.com/bakercloudce/#!/api_install

When I click on "Check DB Connectivity", I get the error.

Upon inspection of the file, /var/www/pubapi/index.php at line 170 there is a function call, logAnalyticMetric(AnalyticType::ApiInteraction,1,NULL,$app_id,$user_id);

This is where the error happens.  If I comment out line 170, the error goes away and I am able to proceed to step 4 of the install doc.

Is this function important?  Can you tell me why this line of code does not function?

**Comment by nin9creative** [comment]
You can delete it...

There was a bug fix submitted for this in the master.

I need to update the 1.1 .zip file with the new version...

https://github.com/bakerframework/bakercloud-ce-api/commit/2ea485e402479094d620a461d8c3a732e6c5abd1

**Comment by nin9creative** [comment]
Fixed in master.
