### ISSUE TITLE
Multiple errors when installing api

### ISSUE THREAD

**Issue by rosstopping** [bakerframework/bakercloud-ce-api#5]
Ran into a few errors while trying to install the api.

Is there a fix for this?

See image below.

![image](https://cloud.githubusercontent.com/assets/302966/3473330/db05e552-02d6-11e4-9ffc-89275c65b842.png)

**Comment by nin9creative** [comment]
Check the PHP version.  It requires > 5.3

**Comment by rosstopping** [comment]
I thought that might be the case. Just checked though and I'm running 5.5.
